import { APP_NAME, BUTTONS, MODIFY_TEXTS } from '../state/texts';

/** UI strings of the original (smpr_esp.lng and captions-formularios.txt), without the & accelerators. */
export const S = {
  appName: APP_NAME,
  menus: {
    archivo: 'Archivo',
    simulacion: 'Simulación',
    utilidades: 'Utilidades',
    opciones: 'Opciones',
    ayuda: 'Ayuda',
    dispositivos: 'Dispositivos',
    nuevo: 'Nuevo Programa',
    abrir: 'Abrir Programa...',
    guardar: 'Guardar Programa',
    guardarComo: 'Guardar Programa Como...',
    salir: 'Salir',
    ejecutar: 'Ejecutar',
    pausar: 'Pausar Simulación',
    reanudar: 'Reanudar Simulación',
    pasoAPaso: 'Paso a paso',
    estadisticas: 'Estadísticas...',
    reiniciar: 'Reiniciar Registros',
    modificarMemoria: 'Modificar una Posición de Memoria...',
    vigilante: 'Vigilante de Memoria...',
    conversion: 'Conversión de bases...',
    entradaManual: 'Entrada de Instrucciones Manualmente...',
    editor: 'Editor Interno...',
    configurar: 'Configurar SimuProc...',
    acercaDe: 'Acerca de...',
    instrucciones: 'Instrucciones soportadas',
    puertos: '- Puertos E/S: -',
    puerto1: '1 - Teclado y Pantalla (E y S) ...',
    puerto8: '8 - Reloj (E)',
    puerto9: '9 - Switches (E) ...',
    puerto13: '13 - PC Speaker (S)',
  },
  groups: {
    registrosProcesador: 'Registros del Procesador',
    registrosGenerales: 'Registros Generales',
    pila: 'Pila ó Stack',
    registrosControl: 'Registros de Control',
    alu: 'ALU',
    memoria: 'Memoria',
    usoMemoria: 'Uso de Memoria y Pila',
    control: 'Control de la Simulación',
    dispositivos: 'Dispositivos de E/S',
    ciclo: 'Ciclo del Procesador',
  },
  hints: {
    pc: 'Program Counter ó Instruction Pointer, Contiene el desplazamiento relativo en el segmento de código donde se está ejecutando el programa actual.',
    mar: 'Memory Address Register',
    mdr: 'Memory Data Register',
    ir: 'Instruction Register',
    bp: 'Base Pointer (Puntero de base de la Pila). Puede cambiar este valor desde un programa, asi: MOV BP, direccion de mem que contenga la direccion.',
    sp: 'Stack Pointer (Puntero de Pila)',
    ax: 'Registro AX (Acumulador)',
    bx: 'Registro BX (base)',
    cx: 'Registro CX (contador)',
    alu: 'Arithmetic Logic Unit',
    z: 'Se Vuelve 1 si el resultado de la operacion = 0.  Si esta Depurando su programa le puede dar Doble Click para un cambio forzado.',
    n: '1 si el resultado de la ultima Operacion = numero negativo',
    c: '1 si hay Acarreo',
    o: '1 si se produce overflow',
    cod: 'Ver o no, Instrucciones Por Codigo de Op',
    autoInstr: '(AutoScroll) Mostrar posición de memoria a la que se accede durante la simulación (Instrucciones)',
    autoVars: '(AutoScroll) Mostrar posición de memoria a la que se accede durante la simulación (Variables)',
    animacion:
      'Desactiva la animación de la simulación para una ejecución mas rápida en caso de que el programa sea muy largo y se tenga un adaptador de grafico lento.',
    velocidad: 'Velocidad de Simulación',
    usoMemoria: 'Indica el Porcentaje de uso de la memoria Simulada',
    usoPila: 'Indica el Porcentaje de uso del espacio actual reservado para la pila',
    pantalla: 'Dispositivo de Salida (Pantalla)',
    teclado: 'Dispositivo de Entrada (Teclado)',
  },
  buttons: {
    cod: 'Cod',
    animacion: 'Animación',
    ejecutar: 'Ejecutar',
    pausar: 'Pausar',
    reanudar: 'Reanudar',
    paso: 'Paso a paso',
    reiniciar: 'Reiniciar Registros',
    mostrar: 'Mostrar',
    ocultar: 'Ocultar',
    min: 'Min',
    max: 'Max',
    aceptar: BUTTONS.aceptar,
    cancelar: BUTTONS.cancelar,
    si: BUTTONS.si,
    no: BUTTONS.no,
    cerrar: 'Cerrar',
    entrarDato: 'Entrar Dato',
    verScroll: 'Ver Scroll Monitor',
    limpiarMonitor: 'Limpiar Monitor',
    modificar: 'Modificar !!',
    ok: 'Ok',
    borrar: 'Borrar',
  },
  memoria: { direccion: 'Dirección', valor: 'Valor' },
  devices: {
    title: 'Dispositivos de E/S',
    intro: 'Estos son los dispositivos de Entrada/Salida.',
    pantalla: 'Pantalla',
    leer: 'Leer del Teclado el dato que se pide',
    decimal: 'Decimal',
    binario: 'Binario',
    ultimoDato: 'Ultimo Dato:',
    binarioLabel: 'binario',
    hintUltimo: 'Ultimo Dato enviado a la Pantalla',
  },
  editor: {
    title: 'Editor Interno de SimuProc',
    tab1: 'Editor 1 (Tipo Memoria)',
    tab2: 'Editor 2 (De Texto)',
    limpiar1: 'Limpiar Editor 1',
    limpiar2: 'Limpiar Editor 2',
    convertirA2: 'Convertir a Editor 2',
    convertirA1: 'Convertir a Editor 1',
    traer: 'Traer Programa desde Memoria Principal a el Editor 1',
    enviar: 'Enviar a Memoria',
    enviarHint: 'Enviar a Memoria de SimuProc',
    cargar: 'Cargar un programa desde un archivo',
    guardar: 'Guardar Programa en un Archivo',
    ejemplos: 'Programas de Ejemplo',
    agregar: 'Agregar Instrucción',
    columnas: { dir: 'Dir', inst: 'Instrucción / Dato', comentario: 'Comentario' },
    linea: 'Linea: ',
    col: '  Col: ',
    usoMemoria: 'Uso de Memoria: ',
    agregarFila: 'Agregar fila',
    borrarFila: 'Borrar',
  },
  modify: {
    title: 'Modificar una Posición de Memoria',
    direccion: 'Dirección',
    valor: 'Valor',
    hintDir: 'Dirección de Memoria (en Hex)',
    hintValor: 'Valor de Dicha dirección: instrucción (MOV AX,BX), dato binario o texto tal como se guarda',
    flags: 'Modificar Flags (Banderas)',
    ok: 'Cambio Exitoso.',
    badDir: MODIFY_TEXTS.badDir,
    indique: MODIFY_TEXTS.indique,
  },
  about: {
    title: 'Acerca de . .',
    subtitle: 'Simulador de un Procesador',
    version: 'Version 1.4.3.0',
    author: 'Vladimir Yepes Bedoya',
    date: 'Febrero 2004',
    banner: 'S I M U P R O C',
    web: 'Página WEB:',
  },
  help: { title: 'Instrucciones soportadas', codigo: 'Código', instruccion: 'Instrucción', descripcion: 'Descripción' },
  saveAs: { title: 'Guardar el Programa en un Archivo', nombre: 'Nombre del archivo', formato: 'Formato' },
  status: { modificado: '*' },
  manual: {
    title: 'Entrada de Instrucciones Manualmente',
    lista: 'Lista de Instrucciones',
    hintLista: 'Lista de Instrucciones (Cod Op - Instruccion [Parametros])',
    dir: 'Dir',
    hintDir: 'Escribir instrucciones manualmente a Partir de esta Direccion de Memoria',
    parametros: 'Parámetros',
    hintParams: 'Escriba aca los parametros de la Instruccion. Dirección de Memoria (en Hex) o registros.',
    comentario: 'Comentario',
    hintComentario: 'Lo que escriba acá se mostrará en la pantalla para esta instrucción en tiempo de ejecución.',
    placeholderComentario: 'Escriba el comentario acá',
    hintOk: 'Cargar Instrucción en Memoria',
    hintBorrar: 'Borra la Ultima Instrucción de la Memoria',
  },
  stats: {
    title: 'Estadísticas de la Simulación',
    instrucciones: 'Instrucciones ejecutadas',
    hintInstrucciones: 'Instrucciones ejecutadas o Cliclos realizados en la simulación',
    duracion: 'Duración',
    velocidad: 'Velocidad de Procesamiento:',
    promedio: 'Tiempo promedio de ejecución:',
    saltos: 'Saltos...',
    condicionales: 'Condicionales:',
    incondicionales: 'Incondicionales:',
    hintCond: 'Son todas las instrucciones como JME, JMA, JEQ, LOOP, JO, etc.',
    pila: 'Manejo de Pila',
    hintPila: 'al terminar el programa, el numero de Push debe ser igual al de Pop, sino su programa tiene errores.',
    otras: 'Otras operaciones..',
    comparaciones: 'Comparaciones:',
    logicas: 'Lógicas con Bits:',
    aritmeticas: 'Aritméticas:',
    desplazamientos: 'Desp Bits:',
    entrada: 'Entrada:',
    salida: 'Salida:',
    mostrarDespues: 'Mostrar después de la ejecución',
    hintMostrar: 'Mostrar Siempre esta ventana después de ejecutar un programa',
  },
  watch: {
    title: 'Vigilante de Memoria',
    intro: 'Puede Vigilar hasta 6 posiciones de Memoria',
    posicion: 'Posición',
    verActivar: 'Ver/Activar',
    dir: 'Dir',
    hintDir: 'Dirección de memoria a vigilar (hex)',
    valorActual: 'Valor Actual',
    ultimos: 'Ultimos 5 Valores',
    hintHistorial: 'Muestra los ultimos 5 valores que ha tenido esta posición',
    pausar: 'Pausar Simulación',
    hintPausar: 'Pausar la Simulación cuando cambie el valor de esta posición',
    pausarIgual: 'Pausar solo si el Valor es =',
    hintPausarIgual: 'Pausa la Simulación solo cuando el valor sea igual al especificado',
    hintValor: 'Escriba un Valor para que la Simulación se pause cuando la posición lo contenga',
    /** Not original texts: how parseCompare reads the value (docs/fidelidad.md, section 30). */
    placeholderValor: 'binario ó 10d',
    formatoValor: 'En binario como las celdas (10 = 2), o decimal con sufijo d (10d = 10)',
    borrarValores: 'Borrar Estos Valores',
  },
  switches: { title: 'Switches - Puerto 9' },
  config: {
    title: 'Configurar SimuProc',
    animacion: 'Opciones de la Animación',
    colorLectura: 'Color de Lectura o Acceso',
    colorEscritura: 'Color de Escritura',
    hintColor: 'Click para seleccionar otro Color',
    coloresDefecto: 'Colores Por Defecto',
    perseguirInstr: 'Perseguir Acceso de Instrucciones',
    perseguirVars: 'Perseguir Acceso de Variables o Datos',
    entradaSalida: 'Opciones de Entrada y Salida',
    capacidadLineas: 'Capacidad de # Lineas en Pantalla',
    hintLineas: 'Buffer del Monitor (# de lineas) min 2, max  15000',
    porDefecto: 'Por Defecto',
    redondear: 'Redondear Numeros de Punto Flotante a:',
    cifras: 'cifras decimales.',
    eliminarCeros: 'Eliminar Ceros decimales sobrantes.',
    avanzado: 'Opciones Avanzadas',
    editarMemoria: 'Permitir editar memoria directamente',
    hintEditar: 'Ud es responsable de colocar valores validos en memoria. Con esta opción un clic en la lista de memoria abre Modificar una Posición de Memoria.',
    ignorar: 'Ignorar Instrucciones no reconocidas',
    hintIgnorar: 'Ignora codigos de operacion no reconocidos en Tiempo de Ejecucion.',
    resetear: 'Resetear estadísticas',
    hintResetear: 'Automaticamente pone en cero las estadisticas al ejecutar un programa desde el principio.',
    mostrarInst: 'Mostrar Instrucción (en vez del código de operación)',
    hintMostrarInst: 'Muestra las instrucciones en memoria en vez del codigo de instruccion.',
  },
} as const;
